# Generated by Django 4.1.5 on 2023-02-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikiquote_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catrgory',
            new_name='Category',
        ),
    ]
