# Generated by Django 4.1.5 on 2023-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiquote_app', '0003_alter_article_create_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='wikiquote_app.category'),
        ),
    ]
